version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "gohttp101"
    ports:
      - "4000:4000"
    env_file: ./.env
    command: [ "./main" ]
