apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohttp101-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gohttp101
  template:
    metadata:
      labels:
        app: gohttp101
    spec:
      containers:
        - name: gohttp101
          image: ghcr.io/devinsightforge/gohttp101:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: "mongo_connection_uri"

---
apiVersion: v1
kind: Service
metadata:
  name: gohttp101-service
spec:
  type: NodePort
  selector:
    app: gohttp101
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4000
      nodePort: 30001
